  swagger: '2.0'
  info:
    title: Cloud Endpoints + App Engine
    description: Sample API on Cloud Endpoints with an App Engine backend
    version: 1.0.0
  host: authcloudrun-x3e22bo5za-an.a.run.app
  schemes:
    - https
  produces:
    - application/json
  x-google-backend:
    address: https://express-dot-moviewer-e9b49.an.r.appspot.com
    jwt_audience: 471626273404-n5gcmacivgbotruui4a1p2nfa0ibtlev.apps.googleusercontent.com
    protocol: h2
  securityDefinitions:
    firebase:
      authorizationUrl: ""
      flow: "implicit"
      type: "oauth2"
      x-google-issuer: https://securetoken.google.com/moviewer-e9b49
      x-google-jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
      x-google-audiences: moviewer-e9b49
  paths:
    /:
      get:
        summary: Greet a user
        operationId: hello
        responses: 
          '200':
            description: A successful response
            schema:
              type: string

    /v1/users/*/account:
      get:
        summary: get user account 
        operationId: allusers
        security:
          - firebase: []
        responses:
          "200":
            description: A successful response
            schema:
              type: string

    /v1/users/account:
      post:
        summary: post user account
        operationId: postUsers 
        security:
          - firebase: []
        responses:
          "201":
            description: A successful response
            schema:
              type: string


    /v1/recipes/all:
      get:
        summary: get all recipes
        operationId: allrecipes
        responses:
          '200':
            description: A successful response
            schema:
              type: string   

    /v1/recipes/*/my_recipe:
      get:
        summary: get my recipes 
        operationId: mypage
        responses:
          '200':
            description: A successful response
            schema:
              type: string

    /v1/recipes/post_recipe:
      post:
        summary: post recipes
        operationId: postRecipe
        responses:
          '201':
            description: A successful response
            schema:
              type: string

    /v1/recipes/del_recipe:
      delete:
        summary: delete recipe
        operationId: deleteRecipe
        security:  
          - firebase: []
        responses:
          "200":
            description: A successful response
            schema:
              type: string

    /v1/recipes/popular:
      get:
        summary: get popular recipes
        operationId: popularRecipes
        responses:
          '200':
            description: A successful Response
            schema:
              type: string   

    /v1/recipes/*/category:
      get:
        summary: get recipes by category
        operationId: categoryRecipe
        responses:
          '200':
            description: A successful response
            schema:
              type: string


    /v1/menus/all:
      get:
        summary: get all menus
        operationId: allmenus
        responses:
          '200':
            description: A successful response
            schema:
              type: string


    /v1/fav/on_fav:
      post:
        summary: post fav
        operationId: postFav
        responses:
          '201':
            description: A successful response
            schema:
              type: string

    /v1/fav/off_fav:
      delete:
        summary: delete fav
        operationId: deleteFav
        responses:
          '200':
            description: A successful response
            schema:
              type: string    


    /v1/comment/my_comment:
      post:
        summary: post comment
        operationId: postComment
        responses:
          '200':
            description: A successful response
            schema:
              type: string


